apiVersion: v1
kind: Service
metadata:
  name: istio-ex-1
  labels:
    app: istio-ex-1
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: client
  selector:
    app: istio-ex-1